[mysql_config]
log = true
show_sql = true 
max_idle_conns = 10
max_open_conns = 100
conn_max_lifetime = 600

[mysql_log]
level = "INFO" # 日志分级 DEBUG, INFO, WARN, ERROR, DPANIC, PANIC, FATAL
log_file = "sql" # 日志文件名
log_path = "./log" # 日志存放路径
max_age = 30  # 最大保存时间 单位 day
rotation_size = 200 # 日志文件滚动size 单位 M
rotation_time = 24 # 日志滚动周期 单位 hour

[mysql_cluster]
default.master = "root:@tcp(127.0.0.1)/database"
default.slave = "root:@tcp(127.0.0.1)/database"
